<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\Core\OrkunPAM.Application\OrkunPAM.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\OrkunPAM.Persistence\OrkunPAM.Persistence.csproj" />
    <ProjectReference Include="..\..\Infrastructure\OrkunPAM.Cryptography\OrkunPAM.Cryptography.csproj" />
    <ProjectReference Include="..\..\Infrastructure\OrkunPAM.Identity\OrkunPAM.Identity.csproj" />
    <ProjectReference Include="..\OrkunPAM.Grpc\OrkunPAM.Grpc.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.102.3" />
    <PackageReference Include="FluentValidation" Version="11.12.0" />
    <PackageReference Include="QuestPDF" Version="2024.3.4" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.62.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Certificate" Version="8.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="8.0.*" />
    <PackageReference Include="Microsoft.OpenApi" Version="3.5.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OrkunPAM.IntegrationTests" />
  </ItemGroup>

</Project>
