<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Infrastructure\OrkunPAM.Cryptography\OrkunPAM.Cryptography.csproj" />
    <ProjectReference Include="..\..\src\Proxy\OrkunPAM.HttpProxy\OrkunPAM.HttpProxy.csproj" />
    <ProjectReference Include="..\..\src\Proxy\OrkunPAM.SqlProxy\OrkunPAM.SqlProxy.csproj" />
    <ProjectReference Include="..\..\src\Proxy\OrkunPAM.SshProxy\OrkunPAM.SshProxy.csproj" />
  </ItemGroup>
</Project>
